#!/bin/sh
# husky

# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 2020-11-10 5:03:08 ├F10: PM┤
#   From: /Users/hughes/Documents/tencent/Project/VBank/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
